modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache License 2.0"

[[mods]]
modId = "creategsrpm"
version = "2.0.2+neoforge-1.21.1"
displayName = "Create GSRPM"
authors = "Clerway"
description = '''
Engineer's Goggles Now Show The RPM Of Your Machines.
'''
logoFile = "icon.png"
displayURL = "https://modrinth.com/mod/creategsrpm"
issueTrackerURL = "https://github.com/2clerway/Create-Goggles-Show-RPM/issues"

[[dependencies.creategsrpm]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creategsrpm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.creategsrpm]]
modId="create"
type="required"
versionRange="6.0.10+mc1.21.1"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "creategsrpm.mixins.json"
