architectury {
    common(enabled_platforms.split(","))
}

dependencies {
    modImplementation("net.fabricmc:fabric-loader:$fabric_loader_version")
    modCompileOnly("maven.modrinth:create-fabric:$create_fabric_version")
    modCompileOnly("com.tterrag.registrate:Registrate:$registrate_forge_version")
}
